### PR TITLE
Add invite, fix typos

### PR DESCRIPTION
**Pull request by IDeletedSystem64**
Add invite command to add bot to servers, or join TMC Discord for support ([0ab4af1](https://github.com/IDeletedSystem64/TheCodingBot/commit/0ab4af1079621f4d3b8d366111e74304113df7e0)
Fix typos in Bot Info (https://github.com/TMC-Software/TheCodingBot/pull/24/commits/3802cb0cef3278cfa2c888f1792bf62a91833e47)
Possibly more, I'm not sure

### CODE REVIEW

**Comment by IDeletedSystem64** [comment]
Why are you doing this GitHub, Explain yourself??

**Comment by Aisuruneko** [comment]
> Why are you doing this GitHub, Explain yourself??

yes

**Comment by IDeletedSystem64** [comment]
I'm trying to throw together a Emote add command, Hopefully I can get it done by release. Otherwise I'll make a seperate PR for a future update.

**Comment by IDeletedSystem64** [comment]
I'm just going to go ahead and mark it as ready for review, I'll do ``emoadd`` in the next release.

**Comment by IDeletedSystem64** [comment]
Uh yeah I forgot, it adds emoadd. May want to set that as hidden or remove it from the PR if it lets you do that

**Review by Aisuruneko — APPROVED** [review]
Nice catch (on the typo lol)

**Pull request merged**
