### PR TITLE
v5 Release Milestone 1-2

### PR DESCRIPTION
**Pull request by Aisuruneko**
The milestone that does it all. This is it.

### CODE REVIEW

**Comment by IDeletedSystem64** [comment]
Lacks Reversi. Unacceptable

**Review by IDeletedSystem64 — COMMENTED** [review]
It's freaking confusing lmao

**Comment by Aisuruneko** [comment]
> Lacks Reversi. Unacceptable

We'll see about that in a future update. Games is something I want to plan on implementing in v5 sometime.

**Comment by Aisuruneko** [comment]
> It's freaking confusing lmao

Like my love life. Complicated.

**Comment by IDeletedSystem64** [comment]
> We'll see about that in a future update. Games is something I want to plan on implementing in v5 sometime.

You should make a Windows 1.0 style ad for TCB after adding in games and find a way to add Reversi. 😝

**Comment by Aisuruneko** [comment]
> > We'll see about that in a future update. Games is something I want to plan on implementing in v5 sometime.
> 
> You should make a Windows 1.0 style ad for TCB after adding in games and find a way to add Reversi. 😝

AND HOW MUCH DO YOU THINK THECODINGBOT FROM TMC SOFTWARE IS WORTH? ONE HUNDREEED DOLLARS? FIVE HUNDREEED? A THOUSAND - EVEN MORE?!?!?! NOOO IT'S JUST FREE! IT'S THECODINGBOT FROM TMC SOFTWARE! P.O. BOX GH TMC-SOFTWARE/THECODINGBOT. EXCEPT FOR BAD GUYS.

**Comment by IDeletedSystem64** [comment]
> AND HOW MUCH DO YOU THINK THECODINGBOT FROM TMC SOFTWARE IS WORTH? ONE HUNDREEED DOLLARS? FIVE HUNDREEED? A THOUSAND - EVEN MORE?!?!?! NOOO IT'S JUST FREE! IT'S THECODINGBOT FROM TMC SOFTWARE! P.O. BOX GH TMC-SOFTWARE/THECODINGBOT. EXCEPT FOR BAD GUYS.

LMFAO

**Comment by Savlac** [comment]
?

**Comment by Aisuruneko** [comment]
> ?

Since when did you have GitHub.....?

**Comment by Savlac** [comment]
I didn't

**Comment by Aisuruneko** [comment]
> I didn't

Oh, lol.

**Comment by Savlac** [comment]
hello give wallet

**Pull request merged**
